[ui]
agent_panel_sort = "priority"

[keys]
prefix = "ctrl+space"

rename_tab = "prefix+r"
resize_mode = "prefix+ctrl+r"
settings = "prefix+ctrl+s"
goto = ["prefix+g", "prefix+s"]

split_vertical = ["prefix+v", "prefix+|"]

focus_pane_left = ["prefix+h", "ctrl+h"]
focus_pane_down = ["prefix+j", "ctrl+j"]
focus_pane_up = ["prefix+k", "ctrl+k"]
focus_pane_right = ["prefix+l", "ctrl+l"]
