(require 'package)

(require 'my-setup)            ; initial setup, libraries and basic stuff
(require 'my-config)           ; Some basic configuration settings
(require 'my-utils)
(require 'my-evil)
(require 'my-org)
(require 'my-dired)
(require 'my-term)
(require 'my-helm)
(require 'my-javascript)
(require 'my-editorconfig)
(require 'my-flycheck)
(require 'my-yasnippet)
(require 'my-company)
(require 'my-hydra)
(require 'my-backup)
(require 'my-projectile)
(require 'my-markdown)
(require 'my-rainbow-delimiters)
(require 'my-magit)
(require 'my-origami)
(require 'my-powerline)
(require 'my-prog)
(require 'my-powerline)
(require 'my-elisp)
(require 'my-visuals)
(require 'my-text-objects)
(require 'my-undo-tree)
(require 'my-bookmarks)
(require 'my-misc)

;;; init.el ends here
